"""
File Export Service
-------------------
Packages all task outputs for a project into a downloadable zip archive.
Handles code, API specs, DB schemas, tests, docs, and DevOps configs.
"""

import io
import json
import zipfile
from typing import Optional

from sqlalchemy.orm import Session

from app.models.database import Task, TaskStatus, Project
from app.utils.logger import logger


# Maps agent name → (filename, content extractor fn)
def _extract_file(agent_name: str, output: dict) -> list[tuple[str, str]]:
    """Returns list of (filename, content) pairs from an agent output dict."""
    files = []

    if agent_name == "code_generator":
        lang = output.get("language", "py")
        ext = {"python": "py", "javascript": "js", "typescript": "ts",
               "go": "go", "java": "java", "rust": "rs"}.get(lang, lang)
        code = output.get("code") or output.get("raw_output", "")
        if code:
            files.append((f"src/main.{ext}", code))
        explanation = output.get("explanation", "")
        if explanation:
            files.append(("src/NOTES.md", f"# Design Notes\n\n{explanation}\n"))

    elif agent_name == "api_designer":
        api = output.get("api_design", output)
        files.append(("api/openapi_spec.json", json.dumps(api, indent=2)))

    elif agent_name == "database_schema":
        sql = output.get("sql_ddl", "")
        schema = output.get("schema", {})
        if sql:
            files.append(("database/schema.sql", sql))
        if schema:
            files.append(("database/schema.json", json.dumps(schema, indent=2)))

    elif agent_name == "testing_agent":
        lang = output.get("language", "python")
        ext = {"python": "py", "javascript": "js", "typescript": "ts"}.get(lang, lang)
        code = output.get("test_code") or output.get("raw_output", "")
        if code:
            files.append((f"tests/test_main.{ext}", code))

    elif agent_name == "documentation_agent":
        doc = output.get("documentation") or output.get("raw_output", "")
        if doc:
            files.append(("README.md", doc))

    elif agent_name == "frontend_generator":
        for i, component in enumerate(output.get("components", [])):
            files.append((f"frontend/components/Component{i+1}.jsx", component))
        for i, style in enumerate(output.get("styles", [])):
            files.append((f"frontend/styles/style{i+1}.css", style))

    elif agent_name == "devops":
        for fname, content in output.get("files", {}).items():
            files.append((fname, content))

    elif agent_name == "security_auditor":
        report = json.dumps(output, indent=2)
        files.append(("reports/security_audit.json", report))

    elif agent_name == "performance_optimizer":
        report = json.dumps(output, indent=2)
        files.append(("reports/performance_report.json", report))

    return files


class FileExportService:

    @staticmethod
    def build_zip(project: Project, tasks: list[Task]) -> bytes:
        """
        Build an in-memory zip of all completed task outputs.
        Returns raw bytes suitable for a StreamingResponse.
        """
        buf = io.BytesIO()

        with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
            # Write a manifest
            manifest_lines = [
                f"# {project.name}",
                f"# Generated by MetaAgent",
                f"",
                f"## Tasks included",
            ]

            for task in tasks:
                if task.status != TaskStatus.COMPLETED or not task.output_data:
                    continue

                agent_name = task.agent_type.value.lower()
                output = task.output_data

                # Resolve "code_generator" etc from the title when agent_type is overloaded
                title_agent = task.title.split(": ")[-1].strip() if ": " in task.title else agent_name
                effective_agent = title_agent if title_agent in (
                    "code_generator", "api_designer", "database_schema", "testing_agent",
                    "documentation_agent", "frontend_generator", "devops",
                    "security_auditor", "performance_optimizer"
                ) else agent_name

                try:
                    files = _extract_file(effective_agent, output)
                except Exception as e:
                    logger.warning(f"Could not extract files from task {task.id}: {e}")
                    files = []

                for filename, content in files:
                    zf.writestr(filename, content)
                    manifest_lines.append(f"- {filename}  (from {effective_agent})")

            zf.writestr("MANIFEST.md", "\n".join(manifest_lines))

        return buf.getvalue()

    @staticmethod
    def get_project_files_summary(tasks: list[Task]) -> list[dict]:
        """Returns a list of {filename, agent, size} for the UI to display."""
        summary = []
        for task in tasks:
            if task.status != TaskStatus.COMPLETED or not task.output_data:
                continue
            agent_name = task.agent_type.value.lower()
            title_agent = task.title.split(": ")[-1].strip() if ": " in task.title else agent_name
            try:
                files = _extract_file(title_agent, task.output_data)
                for fname, content in files:
                    summary.append({
                        "filename": fname,
                        "agent": title_agent,
                        "size_bytes": len(content.encode("utf-8")),
                    })
            except Exception:
                pass
        return summary